import { getAllRows, appendRow, updateRow, deleteRow, getHeaders, initSheets, getSheetId } from './gsheets.js';

let cache = {};

export async function initDb() {
  await initSheets();
  await refreshCache();
  const admin = await queryOne("SELECT * FROM users WHERE username = ?", ['admin']);
  if (!admin) {
    const bcrypt = await import('bcryptjs');
    const hash = await bcrypt.hash('admin123', 10);
    await execute("INSERT INTO users (username, email, password_hash, role) VALUES (?,?,?,?)", ['admin', 'admin@dhiblawe.local', hash, 'super_admin']);
    const eh = await bcrypt.hash('entry123', 10);
    await execute("INSERT INTO users (username, email, password_hash, role) VALUES (?,?,?,?)", ['dataentry', 'data@dhiblawe.local', eh, 'data_entry']);
    const vh = await bcrypt.hash('view123', 10);
    await execute("INSERT INTO users (username, email, password_hash, role) VALUES (?,?,?,?)", ['viewer', 'view@dhiblawe.local', vh, 'view_only']);
  }
  const settingsExist = await queryOne("SELECT * FROM settings WHERE key = ?", ['company_name']);
  if (!settingsExist) {
    for (const [k, v] of [['company_name', 'Dhiblawe WaterFlow'], ['company_logo', ''], ['company_phone', '+254 700 000 000'], ['invoice_prefix', 'DWF-'], ['report_title', 'Water Delivery Report'], ['report_footer', 'System Generated by Dhiblawe WaterFlow Operations System'], ['report_footer_message', 'Please settle your outstanding balance at your earliest convenience.']]) {
      await execute("INSERT INTO settings (key, value) VALUES (?,?)", [k, v]);
    }
  }
}

async function refreshCache() {
  for (const t of ['users', 'clients', 'plate_numbers', 'trips', 'payments', 'deposits', 'settings']) {
    cache[t] = await getAllRows(t);
  }
}

function evalExpr(expr, row) {
  expr = expr.trim();
  if (expr.includes('-')) {
    const parts = expr.split('-').map(s => s.trim());
    let result = 0;
    for (let i = 0; i < parts.length; i++) {
      const val = Number(row[parts[i]]) || 0;
      result = i === 0 ? val : result - val;
    }
    return result;
  }
  if (expr.includes('+')) {
    return expr.split('+').reduce((s, p) => s + (Number(row[p.trim()]) || 0), 0);
  }
  return Number(row[expr]) || 0;
}

function parseSql(sql) {
  const tableMatch = sql.match(/\bFROM\s+(\w+)/i);
  const table = tableMatch ? tableMatch[1] : null;

  const isInsert = /^INSERT\s+INTO/i.test(sql);
  const isUpdate = /^UPDATE\s+/i.test(sql);
  const isDelete = /^DELETE\s+FROM/i.test(sql);
  const isSelect = /^SELECT\s+/i.test(sql);

  let whereFull = '';
  const whereIdx = sql.search(/\bWHERE\b/i);
  if (whereIdx >= 0) {
    const rest = sql.slice(whereIdx + 5);
    let end = rest.length;
    for (const kw of ['ORDER BY', 'LIMIT', 'OFFSET', 'RETURNING']) {
      const idx = rest.search(new RegExp(`\\b${kw}\\b`, 'i'));
      if (idx >= 0 && idx < end) end = idx;
    }
    whereFull = rest.slice(0, end).trim();
  }

  const orderMatch = sql.match(/\bORDER\s+BY\s+(\w+(?:\.\w+)?)\s*(ASC|DESC)?/i);
  const limitMatch = sql.match(/\bLIMIT\s+(\d+)/i);
  const offsetMatch = sql.match(/\bOFFSET\s+(\d+)/i);
  const returningMatch = /\bRETURNING\s+id\b/i.test(sql);

  const joinMatches = [...sql.matchAll(/\bJOIN\s+(\w+)\s+(?:\w+\s+)?ON\s+(\w+)\.(\w+)\s*=\s*(\w+)\.(\w+)/gi)];

  const aggCountMatch = sql.match(/COUNT\s*\(\s*\*?\s*\)\s+as\s+(\w+)/i);
  const aggMaxMatch = sql.match(/MAX\s*\(\s*(\w+(?:\.\w+)?)\s*\)\s+as\s+(\w+)/i);
  const aggSumMatch = sql.match(/COALESCE\s*\(\s*SUM\s*\(\s*([^)]+)\s*\)\s*,\s*0\s*\)\s+as\s+(\w+)/i);

  const colMatch = sql.match(/^SELECT\s+(.+?)\s+FROM/i);
  const columns = colMatch ? colMatch[1].split(',').map(c => c.trim()) : [];

  const conditions = [];
  if (whereFull && whereFull !== '1=1') {
    const orBlocks = whereFull.split(/\s+OR\s+/i);
    for (const block of orBlocks) {
      const andParts = block.replace(/^\(|\)$/g, '').split(/\s+AND\s+/i);
      const condGroup = [];
      for (const part of andParts) {
        const trimmed = part.trim();
        if (trimmed === '1=1') continue;
        const m = trimmed.match(/(\w+(?:\.\w+)?)\s*(=|>=|<=|!=|>|<)\s*(?:\?|(\d+(?:\.\d+)?|'[^']*'))/);
        if (m) {
          const field = m[1].includes('.') ? m[1].split('.')[1] : m[1];
          const isParam = m[3] === undefined;
          const rawVal = isParam ? null : (m[3].startsWith("'") ? m[3].slice(1, -1) : (m[3].includes('.') ? parseFloat(m[3]) : parseInt(m[3])));
          condGroup.push({ field, operator: m[2], isParam, rawVal });
        }
      }
      if (condGroup.length > 0) conditions.push(condGroup);
    }
  }

  let insertCols = [], insertVals = [];
  if (isInsert) {
    const cm = sql.match(/INSERT\s+INTO\s+\w+\s*\(([^)]+)\)/i);
    if (cm) insertCols = cm[1].split(',').map(c => c.trim());
    const vm = sql.match(/VALUES\s*\(([^)]+)\)/i);
    if (vm) insertVals = vm[1].split(',').map(v => v.trim());
  }

  let updateSets = [];
  if (isUpdate) {
    const sm = sql.match(/SET\s+(.+?)(?:WHERE|$)/i);
    if (sm) {
      updateSets = sm[1].split(',').map(s => {
        const eqIdx = s.indexOf('=');
        return { col: s.slice(0, eqIdx).trim(), hasParam: s.slice(eqIdx + 1).trim() === '?' };
      });
    }
  }

  return { table, isSelect, isInsert, isUpdate, isDelete, whereFull, conditions, orderMatch, limitMatch, offsetMatch, returningMatch, joinMatches, columns, insertCols, insertVals, updateSets, aggCountMatch, aggSumMatch, aggMaxMatch };
}

function matchRow(row, conditions, params) {
  let paramIdx = 0;
  if (conditions.length === 0) return true;

  for (const group of conditions) {
    let groupMatch = true;
    for (const cond of group) {
      let condMatch;
      if (cond.isParam) {
        const pv = params[paramIdx++];
        condMatch = compare(row[cond.field], pv, cond.operator);
      } else {
        condMatch = compare(row[cond.field], cond.rawVal, cond.operator);
      }
      if (!condMatch) { groupMatch = false; break; }
    }
    if (groupMatch) return true;
  }
  return false;
}

function compare(rowVal, target, operator) {
  const rv = (rowVal ?? '').toString();
  const tv = (target ?? '').toString();
  switch (operator) {
    case '=': return rv === tv;
    case '!=': return rv !== tv;
    case '>=': return Number(rv) >= Number(tv);
    case '<=': return Number(rv) <= Number(tv);
    case '>': return Number(rv) > Number(tv);
    case '<': return Number(rv) < Number(tv);
    default: return true;
  }
}

export async function queryAll(sql, params = []) {
  const parsed = parseSql(sql);
  let rows = await getTableData(parsed.table);

  for (const join of parsed.joinMatches) {
    const joinTable = join[1];
    const localField = join[4];      // trips.client_id
    const foreignField = join[5];    // clients.id
    const joinRows = await getTableData(joinTable);
    const joinMap = {};
    for (const jr of joinRows) joinMap[jr[foreignField]] = jr;
    rows = rows.map(row => {
      const matched = joinMap[row[localField]];
      if (matched) {
        row.client_name = matched.name;
        row.plate_number = matched.plate || matched.plate_number;
      }
      return row;
    });
  }

  rows = rows.filter(row => matchRow(row, parsed.conditions, params));

  if (parsed.aggCountMatch || parsed.aggSumMatch || parsed.aggMaxMatch) {
    let result;
    if (parsed.aggCountMatch) {
      result = rows.length;
    } else if (parsed.aggSumMatch) {
      const expr = parsed.aggSumMatch[1].trim();
      result = rows.reduce((s, r) => s + evalExpr(expr, r), 0);
    } else if (parsed.aggMaxMatch) {
      const field = parsed.aggMaxMatch[1].includes('.') ? parsed.aggMaxMatch[1].split('.')[1] : parsed.aggMaxMatch[1];
      result = rows.reduce((m, r) => Math.max(m, Number(r[field]) || 0), 0);
    }
    const alias = parsed.aggCountMatch?.[1] || parsed.aggSumMatch?.[2] || parsed.aggMaxMatch?.[2] || 'total';
    return [{ [alias]: result, total: result }];
  }

  if (parsed.orderMatch) {
    const field = parsed.orderMatch[1].includes('.') ? parsed.orderMatch[1].split('.')[1] : parsed.orderMatch[1];
    const dir = parsed.orderMatch[2] || 'ASC';
    rows.sort((a, b) => {
      const av = (a[field] ?? '').toString().toLowerCase();
      const bv = (b[field] ?? '').toString().toLowerCase();
      const cmp = av.localeCompare(bv);
      return dir.toUpperCase() === 'DESC' ? -cmp : cmp;
    });
  }

  if (parsed.limitMatch) {
    const offset = parsed.offsetMatch ? parseInt(parsed.offsetMatch[1]) : 0;
    rows = rows.slice(offset, offset + parseInt(parsed.limitMatch[1]));
  }

  const hasSpecificCols = parsed.columns.length > 0 && !parsed.columns.some(c => c.includes('*'));
  if (hasSpecificCols) {
    rows = rows.map(row => {
      const obj = {};
      for (const col of parsed.columns) {
        if (col.includes(' as ')) {
          const [expr, alias] = col.split(/\s+as\s+/i);
          obj[alias.trim()] = row[expr.includes('.') ? expr.split('.')[1] : expr.trim()];
        } else if (!col.includes('.')) {
          obj[col] = row[col];
        }
      }
      return obj;
    });
  }

  return rows;
}

export async function queryOne(sql, params = []) {
  const rows = await queryAll(sql, params);
  return rows[0] || null;
}

export async function execute(sql, params = []) {
  const parsed = parseSql(sql);

  if (parsed.isInsert) {
    const headers = await getHeaders(parsed.table);
    const rows = await getTableData(parsed.table, true);
    let maxId = 0;
    for (const r of rows) maxId = Math.max(maxId, Number(r.id) || 0);
    const newId = maxId + 1;

    const data = { id: newId };
    let paramIdx = 0;
    for (let i = 0; i < parsed.insertCols.length; i++) {
      const val = parsed.insertVals[i] === '?' ? params[paramIdx++] : parsed.insertVals[i].replace(/^'(.*)'$/, '$1');
      data[parsed.insertCols[i]] = val;
    }
    if (!data.created_at) data.created_at = new Date().toISOString();
    if (!data.updated_at) data.updated_at = new Date().toISOString();
    if (!data.is_active) data.is_active = 1;
    if (parsed.table === 'trips' && !data.deposit_used) data.deposit_used = 0;
    if (parsed.table === 'deposits' && !data.remaining) data.remaining = data.amount;

    await appendRow(parsed.table, data, headers);
    cache[parsed.table] = await getAllRows(parsed.table);

    if (parsed.returningMatch) {
      const created = await queryOne(`SELECT * FROM ${parsed.table} WHERE id = ?`, [newId]);
      return { rows: [created || { id: newId }] };
    }
    return { rows: [{ id: newId }] };
  }

  if (parsed.isUpdate) {
    const headers = await getHeaders(parsed.table);
    let rows = await getTableData(parsed.table, true);

    let paramIdx = 0;
    const updates = {};
    for (const s of parsed.updateSets) {
      if (s.hasParam) updates[s.col] = params[paramIdx++];
    }

    for (let i = 0; i < rows.length; i++) {
      if (!matchRow(rows[i], parsed.conditions, params)) continue;
      for (const [col, val] of Object.entries(updates)) rows[i][col] = val;
      rows[i].updated_at = new Date().toISOString();
      const rowData = {};
      for (const h of headers) rowData[h] = rows[i][h] !== undefined && rows[i][h] !== null ? rows[i][h] : '';
      await updateRow(parsed.table, rows[i].__rowIndex, rowData, headers);
    }

    cache[parsed.table] = await getAllRows(parsed.table);
    return { rows: [] };
  }

  if (parsed.isDelete) {
    let rows = await getTableData(parsed.table, true);
    for (let i = rows.length - 1; i >= 0; i--) {
      if (!matchRow(rows[i], parsed.conditions, params)) continue;
      await deleteRow(parsed.table, rows[i].__rowIndex);
    }
    cache[parsed.table] = await getAllRows(parsed.table);
    return { rows: [] };
  }

  return { rows: [] };
}

export async function transaction(fn) {
  await fn();
}

export function save() {}

async function getTableData(table, includeRowIdx = false) {
  if (!cache[table]) cache[table] = await getAllRows(table);
  const rows = cache[table];
  if (includeRowIdx) return rows;
  return rows.map(({ __rowIndex, ...rest }) => rest);
}
